library(readr)
#install.packages("lubridate")

X2_Ethereum <- read_delim("Data/2_Ethereum.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X3_XRP <- read_delim("Data/3_XRP.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X4_Bitcoin_Cash <- read_delim("Data/4_Bitcoin-Cash.csv", ",", escape_double = FALSE)
X5_Tether <- read_delim("Data/5_Tether.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X6_Bitcoin_SV <- read_delim("Data/6_Bitcoin-SV.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X7_Litecoin <- read_delim("Data/7_Litecoin.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X7_Tether <- read_delim("Data/7_Tether.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X8_EOS <- read_delim("Data/8_EOS.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X9_Binance_Coin <- read_delim("Data/9_Binance-Coin.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X10_Tezos <- read_delim("Data/10_Tezos.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X11_ChainLink <-read_delim("Data/11_Chainlink.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X12_Cardano <- read_delim("Data/12_Cardano.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X13_Monero <- read_delim("Data/13_Monero.csv",",", escape_double = FALSE, trim_ws = TRUE)
X14_Stellar  <- read_delim("Data/14_Stellar.csv",",", escape_double = FALSE, trim_ws = TRUE)
X15_TRON  <- read_delim("Data/15_TRON.csv",",", escape_double = FALSE, trim_ws = TRUE)
X16_Huobi_Token <- read_delim("Data/16_Huobi-Token.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X17_UNUS_SED_LEO <- read_delim("Data/17_UNUS-SED-LEO.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X18_EthereumClassic <- read_delim("Data/18_Ethereum-Classic.csv",",", escape_double = FALSE, trim_ws = TRUE)
X19_Neo <- read_delim("Data/19_Neo.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X20_Dash <- read_delim("Data/20_Dash.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X21_CryptoCoin <- read_delim("Data/21_Crypto.com-Coin.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X22_HedgeTrade <- read_delim("Data/22_HedgeTrade.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X23_Cosmos <- read_delim("Data/23_Cosmos.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X24_IOTA <- read_delim("Data/24_IOTA.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X25_Maker <- read_delim("Data/25_Maker.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X26_Zcash <- read_delim("Data/26_Zcash.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X27_Ontology <- read_delim("Data/27_Ontology.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X28_NEM <- read_delim("Data/26_NEM.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X29_USD_Coin <- read_delim("Data/29_USD-Coin.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X30_USD_Coin <- read_delim("Data/30_Basic-Attention-Token.csv", ",", escape_double = FALSE, trim_ws = TRUE)
X31_Dogecoin <- read_delim("Data/31_Dogecoin.csv", ",", escape_double = FALSE, trim_ws = TRUE)

time <- c("15/11/2016", "5/2/2020")
ymd(time)


