library(readr)


X2_Ethereum <- read_delim("Data/2_Ethereum.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X3_XRP <- read_delim("Data/3_XRP.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X4_Bitcoin_Cash <- read_delim("Data/4_Bitcoin-Cash.csv", ";", escape_double = FALSE)
X5_Bitcoin_SV <- read_delim("Data/5_Bitcoin-SV.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X6_Litecoin <- read_delim("Data/6_Litecoin.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X7_Tether <- read_delim("Data/7_Tether.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X8_EOS <- read_delim("Data/8_EOS.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X9_Binance_Coin <- read_delim("Data/9_Binance-Coin.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X12_Monero <- read_delim("Data/12_Monero.csv",";", escape_double = FALSE, trim_ws = TRUE)
X13_TRON  <- read_delim("Data/13_TRON.csv",";", escape_double = FALSE, trim_ws = TRUE)
X14_Stellar  <- read_delim("Data/14_Stellar.csv",";", escape_double = FALSE, trim_ws = TRUE)
X15_EthereumClassic <- read_delim("Data/15_Ethereum-Classic.csv",";", escape_double = FALSE, trim_ws = TRUE)
X16_Chainlink <- read_delim("Data/16_Chainlink.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X17_Dash <- read_delim("Data/17_Dash.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X18_Huobi_Token <- read_delim("Data/18_Huobi-Token.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X19_UNUS_SED_LEO <- read_delim("Data/19_UNUS-SED-LEO.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X20_Neo <- read_delim("Data/20_Neo.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X21_Cosmos <- read_delim("Data/21_Cosmos.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X22_IOTA <- read_delim("Data/22_IOTA.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X23_CryptoCoin <- read_delim("Data/23_Crypto.com-Coin.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X24_HedgeTrade <- read_delim("Data/24_HedgeTrade.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X25_Zcash <- read_delim("Data/25_Zcash.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X26_NEM <- read_delim("Data/26_NEM.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X27_Maker <- read_delim("Data/27_Maker.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X28_Ontology <- read_delim("Data/28_Ontology.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X29_KickToken <- read_delim("Data/29_KickToken.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X30_USD_Coin <- read_delim("Data/30_USD-Coin.csv", ";", escape_double = FALSE, trim_ws = TRUE)
X31_Dogecoin <- read_delim("Data/31_Dogecoin.csv", ";", escape_double = FALSE, trim_ws = TRUE)



View(X15_EthereumClassic)
